### ISSUE TITLE
Renaming FitsRelation.loadOneTable

### ISSUE THREAD

**Issue by ChristianArnault** [JulienPeloton/spark-fits#33]
Suggested: 
Rename FitsRelation.loadOneTable => FitsRelation.loadOneHDU

(avoid using "table")

CA

**Comment by JulienPeloton** [comment]
Good catch. Done in https://github.com/JulienPeloton/spark-fits/commit/524b0e4a800a6019fe025ecdd0e8a6efcadb5448
